---
# Version 0.1
- hosts: rasp
  remote_user: pi
  become: yes
  become_method: sudo
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist
    - name: Reboot if required
      shell: sleep 10 && /sbin/shutdown -r now 'Rebooting after update'
      args:
        removes: /var/run/reboot-required
      async: 300
      poll: 0
      ignore_errors: true
    - name: Wait for system to become reachable again
      wait_for_connection:
        delay: 60
        timeout: 300
